# Generated by Django 5.1 on 2024-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(choices=[('lg', 'Luís Gomes'), ('pdf', 'Pau dos Ferros'), ('sm', 'São Miguel')], max_length=100)),
                ('curso', models.CharField(choices=[('info', 'Informática'), ('api', 'Apicultura'), ('ali', 'Alimentos')], max_length=100)),
            ],
        ),
    ]
