# Generated by Django 5.1 on 2024-08-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_cidade_alter_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(choices=[('lg', 'Luís Gomes'), ('pdf', 'Pau dos Ferros'), ('sm', 'São Miguel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('info', 'Informática'), ('api', 'Apicultura'), ('ali', 'Alimentos')], max_length=100),
        ),
    ]
