# Generated by Django 5.1 on 2024-08-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interesse',
            new_name='Hobbies',
        ),
    ]
