# Generated by Django 5.1 on 2024-08-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_rename_interesse_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='image_curso',
            field=models.ImageField(default=0, upload_to='imagens/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobbies',
            name='image_hobbie',
            field=models.ImageField(default=0, upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
